ALTER TABLE buildings
    ADD COLUMN IF NOT EXISTS map_rotation_degrees INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS map_grid_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS map_grid_cell_size DOUBLE PRECISION NOT NULL DEFAULT 48,
    ADD COLUMN IF NOT EXISTS map_grid_offset_x DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS map_grid_offset_y DOUBLE PRECISION NOT NULL DEFAULT 0;
